import{a as q,S as P,i}from"./assets/vendor-DvfmeZXB.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const M="https://pixabay.com/api/",$="53364265-bba438c586e7b8abf4f224af4";async function f(t,r=1){try{return(await q(M,{params:{key:$,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}})).data}catch(a){throw new Error(a)}}let R=new P(".gallery a",{captionsData:"alt",captionDelay:250});function m(t){const r=document.querySelector(".gallery"),a=t.map(({webformatURL:s,largeImageURL:e,tags:o,likes:l,views:w,comments:v,downloads:S})=>`
      <a class="gallery-item" href="${e}">
        <div class="photo-card">
          <img src="${s}" alt="${o}" loading="lazy" />
          <div class="info">
            <p class="info-item"><b>Likes:</b> ${l}</p>
            <p class="info-item"><b>Views:</b> ${w}</p>
            <p class="info-item"><b>Comments:</b> ${v}</p>
            <p class="info-item"><b>Downloads:</b> ${S}</p>
          </div>
        </div>
      </a>`).join("");r.insertAdjacentHTML("beforeend",a),R.refresh()}const O=document.querySelector(".gallery");function x(){O.innerHTML=""}const y=document.querySelector(".loader");function g(){y.classList.remove("hidden")}function d(){y.classList.add("hidden")}const p=document.querySelector(".btn-loadmore");function b(){p.classList.remove("hidden")}function c(){p.classList.add("hidden")}const L=document.querySelector(".form"),h=L.querySelector('input[name="search-text"]'),B=document.querySelector(".btn-loadmore");let u="",n=1;d();c();L.addEventListener("submit",H);B.addEventListener("click",A);async function H(t){t.preventDefault();const r=h.value.toLowerCase().trim();if(!r){i.warning({message:"Please enter a search query!",position:"topRight"});return}u=r,n=1,x(),g(),c();try{const a=await f(u,n);if(a.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(a.hits),h.value="";const s=Math.ceil(a.totalHits/a.hits.length);n<s?b():(i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c())}catch{i.error({message:"Something went wrong. Please try again later.",position:"topRight"}),c()}finally{d()}}async function A(){n++,g(),c();try{const t=await f(u,n);m(t.hits),D();const r=Math.ceil(t.totalHits/t.hits.length);n>=r?(i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c()):b()}catch{i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{d()}}function D(){if(n===1)return;const t=document.querySelector(".gallery .gallery-item");if(!t)return;const{height:r}=t.getBoundingClientRect();requestAnimationFrame(()=>{window.scrollBy({top:r*2,behavior:"smooth"})})}
//# sourceMappingURL=index.js.map
